import os
from typing import Any, Dict, List

from iii import InitOptions, Logger, register_worker

iii = register_worker(
    os.environ.get("III_URL", "ws://10.0.2.57:49134"),
    InitOptions(worker_name="math-worker"),
)
logger = Logger()


def run_inference_handler(payload: Dict[str, Any]) -> Dict[str, Any]:
    messages = payload.get("messages", [])
    last_message = messages[-1].get("content", "") if messages else ""

    logger.info(f"inference::run_inference called with {len(messages)} messages")

    # Mock LLM response — demonstrates distributed RPC without heavy ML deps
    response = (
        f"[Inference Worker] Received your message: '{last_message}'. "
        f"This response was generated by the Python inference worker on VM1 "
        f"and routed through the TypeScript caller worker on VM2 via iii-bridge."
    )

    return {
        "id": "chatcmpl-mock-001",
        "object": "chat.completion",
        "model": "mock-inference-v1",
        "choices": [
            {
                "index": 0,
                "message": {
                    "role": "assistant",
                    "content": response,
                },
                "finish_reason": "stop",
            }
        ],
        "usage": {
            "prompt_tokens": len(last_message.split()),
            "completion_tokens": len(response.split()),
            "total_tokens": len(last_message.split()) + len(response.split()),
        },
    }


iii.register_function("inference::run_inference", run_inference_handler)

print("Inference worker started - listening for calls")
